version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
      - FORCE_HTTPS=false
      - FORCE_SEED=true
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço para desenvolvimento (opcional)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    profiles:
      - dev
